stages:
  - publish

to_gem:
  stage: publish
  image: ruby:3.0.3
  script:
    - mkdir -p ~/.gem
    - touch ~/.gem/credentials
    - chmod 0600 ~/.gem/credentials
    - 'printf -- "---\n:rubygems_api_key: $GEM_HOST_API_KEY\n" > ~/.gem/credentials'
    - RELEASE_VERSION=$(cat VERSION.md)
    - GEM_NAME=json_requester-$RELEASE_VERSION.gem
    - gem build json_requester.gemspec
    - gem push $GEM_NAME
  only:
    - master